### ISSUE TITLE
[BUG] Missing tag produces missing title

### ISSUE THREAD

**Issue by gabor-boros** [gabor-boros/minutes#38]
**Describe the bug**

Using Clockify and the settings below, both `Task` and `Summary` columns' values are missing if no `tag` is set.

**To Reproduce**

1. set the specified config
2. create a new entry in Clockify with a title set, but no task or tags are assigned
3. run `minutes`

**Expected behavior**

The `Summary` field should have value, regardless of the missing `Task`.

**Screenshots**

N/A

**System information:**

 - OS name: All OS
 - OS version: Any version
 - Version (output of `minutes --version`): `minutes version 0.2.3, commit 31e9656 (2021-11-08T07:00:12Z)`

**List of flags used:**

N/A

**Additional context**

```toml
# Source config
source = "clockify"
source-user = "<hidden>"

clockify-url = "https://api.clockify.me"
clockify-api-key = "<hidden>"
clockify-workspace = "<hidden>"

# Target config
target = "tempo"
target-user = "gabor-boros"

tempo-url = "<hidden>"
tempo-username = "gabor-boros"
tempo-password = "<hidden>"

# General config
tags-as-tasks = true
tags-as-tasks-regex = '[A-Z]{2,7}-\d{1,6}'

round-to-closest-minute = true
force-billed-duration = true

date-format = "2006-01-02"

table-column-config = {
    summary = {
        widthmax = 40
    },
    end = {
        hidden = true
    },
    project = {
        hidden = true
    }
}
```
